
BUILD_DIR := build
CC := gcc
CXX := g++
AS := as
AR := ar

OSNAME := windows
ARCHNAME := ix86

CFLAGS := -O2 -Wall -std=c99 -fno-strict-aliasing -DDEBUG
CXXFLAGS := -O2 -Wall -DDEBUG

OBJS := $(BUILD_DIR)/common.o \
        $(BUILD_DIR)/sehpp.o \
        $(BUILD_DIR)/seh-support.o \
        $(BUILD_DIR)/seh.o

TARGETS = $(BUILD_DIR)/libseh.a

include rules.mk

